# Generated by Django 3.2.8 on 2021-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.ImageField(null=True, upload_to='events/', verbose_name='Image'),
        ),
    ]
