# Generated by Django 3.2.8 on 2021-10-23 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('confirmation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('accepted_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('declined_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
    ]
