# Generated by Django 3.2.8 on 2021-10-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
        ('participants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events_app.event'),
            preserve_default=False,
        ),
    ]
