# Generated by Django 3.2.8 on 2021-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants_app', '0002_participant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='Invitation accepted'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
    ]
